services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: greenthumb
      POSTGRES_PASSWORD: greenthumb
      POSTGRES_DB: greenthumb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  db-init:
    image: postgres:15
    depends_on:
      - db
    volumes:
      - ./sql:/sql
    environment:
      PGPASSWORD: greenthumb
    entrypoint: >
      bash -c "
        until pg_isready -h db -U greenthumb; do sleep 1; done &&
        psql -h db -U greenthumb -d greenthumb -f /sql/schema.sql &&
        psql -h db -U greenthumb -d greenthumb -f /sql/seed.sql
        sleep 3 &&
      "

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://greenthumb:greenthumb@db:5432/greenthumb
    depends_on:
      - db-init
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: yarn build

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend

volumes:
  pgdata: