services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: greenthumb
      POSTGRES_PASSWORD: greenthumb
      POSTGRES_DB: greenthumb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U greenthumb"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://greenthumb:greenthumb@db:5432/greenthumb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000/health-check"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  pgdata: